// THIS IS AN AUTOGENERATED FILE BY CREATE-WEB3-DAPP

export type CW3DConfig = {
	mainnetName: string;
	mainnetChainId: number;
	testnetChainId: number;
	testnetChainName: string;
};

const config = {
	mainnetName: "arb-mainnet",
	mainnetChainId: 42161,
	testnetChainId: 421614,
	testnetChainName: "arb-sepolia",
} as const satisfies CW3DConfig;

export default config; 